service: hello-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  memorySize: 128
  timeout: 3


functions:
  hello:
    handler: handler.hello
    # memorySize: 128
    # timeout: 3
  add:
    handler: add.add
    memorySize: 256
    timeout: 10
    events:
      - http:
          path: math/add
          method: post
          cors: true

